version: '3.9'
volumes:
  pg_data: {}
networks:
  native_cloud: {}
services:
  postgres:
    image: postgres:14.2
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 1234:5432
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - native_cloud
  backend:
    image: dimmaryanto93/springboot-app:v4
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=mysecretpassword
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    networks:
      - native_cloud