apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  labels:
    app: springboot
    tier: backend
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot
      tier: backend
      env: dev
  template:
    metadata:
      labels:
        app: springboot
        tier: backend
        env: dev
    spec:
      containers:
      - name: springboot-app
        image: docker.io/dimmaryanto93/springboot-app:v3
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://postgres:5432/postgres