apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    tier: db
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      tier: db
      env: dev
  template:
    metadata:
      labels:
        app: postgres
        tier: db
        env: dev
    spec:
      containers:
      - name: postgres
        image: postgres:14.2
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: mysecretpassword