apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    tier: db
    env: dev
spec:
  selector:
    app: postgres
    tier: db
    env: dev
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP